image: ubuntu

stages:
  - test
  - test_future

before_script:
  - apt-get update -y && apt-get install -y python python3 python-tox

run_tests_default:
  stage: test
  script: tox -e py36

run_tests_py37:
  stage: test_future
  script: tox -e py37
  allow_failure: true
