image: ubuntu

stages:
  - test
  - test_past

before_script:
  - apt-get update -y && apt-get install -y python python3 python-tox

run_tests_default:
  stage: test
  script: tox -e py36

run_tests_py27:
  stage: test_past
  script: tox -e py27
  allow_failure: true